---
apiVersion: helm.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: osdu-istio
  namespace: istio-system
spec:
  releaseName: osdu-istio
  dependsOn:
  - name: istio-operator
  chart:
    spec:
      chart: ./osdu-istio
      sourceRef:
        kind: GitRepository
        name: helm-charts-azure
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: istio-system
  values:
    global:
      azure:
        podIdentityAuthEnabled: false
