---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: token-service
  namespace: dev-sample
spec:
  releaseName: token-service
  dependsOn:
  - name: default-service
    namespace: osdu-azure
  chart:
    spec:
      chart: ./charts/self-managed-service
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: dev-sample
  values:
    replicaCount: 1
    ingress:
      issuer: letsencrypt-prod-dns
      enableKeyvaultCert: false
    service:
      type: ClusterIP
      port: 80
