---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-istio
  namespace: istio-system
spec:
  values:
    global:
      azure:
        tenant: a7006dec-4697-4f6c-9fb1-583c0d4b3e19
        appid: 8d49d0b6-24ba-404f-9f7e-6a0811ed9162
