---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: self-managed-base
  namespace: osdu-azure
spec:
  values:
    fullnameOverride: osdu-svc
    azure:
      tenant: 9f784c1c-28b2-4cef-8ac3-c503e04c906a
      subscription: 46932cf8-37d9-4d41-98f8-1bf4bec9dbaf
      resourcegroup: osdu-self-cpliffd-s01d-rg
      identity: osdu-self-cpliffd-s01d-osdu-identity
      identity_id: e8ffd102-5cdf-4962-8ee6-61271ad7811c
      keyvault: osdu-self-cpliff-s01d-kv
      appid: 5002b947-492a-42c4-88db-cd3777cc8688
      oidAuthEnabled: false
    resourceLimits:
      defaultCpuRequests: "100m"
      defaultMemoryRequests: "800Mi"
      defaultCpuLimits: "1000m"
      defaultMemoryLimits: "2Gi"
    identity:
      name: osdu-identity
